[package]
name = "rdecimal"
version = "0.1.0"
authors = ["std"]
edition = "2018"

[features]
default = ["serde"]

[dependencies]
num = "0.2"
serde = { version = "1.0", optional = true }

[dev-dependencies]
rand = "0.7"
serde_json = "1.0"
serde_derive = "1.0"
